---
abstract: 'API Handle'
author:
  - 'Nour Sharabash <amirite@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: API-Handle
requires:
  Carp: 0
  Data::Dumper: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Role: 0
  Nour::Config: 0
  Nour::Database: 0
  Nour::Printer: 0
  OX::OAuth: 0
  String::CamelCase: 0
  Tie::Hash::Indexed: 0
  URI: 0
  XML::TreePP: 0
  bytes: 0
  feature: 0
  namespace::autoclean: 0
resources:
  bugtracker: https://github.com/quran/api-handle/issues
  repository: git://github.com/quran/api-handle.git
version: 0.02
